modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="the_point_of_noreturn"
version="1.0.0"
displayName="The Point Of Noreturn"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.the_point_of_noreturn]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.the_point_of_noreturn]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration